// packages/desktop/ui/src/lib/components/sidebar.svelte
<script lang="ts">
  import { Terminal, Plus, Search, ChevronLeft, ChevronRight, Trash2, Pencil } from "@lucide/svelte";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import type { ConnectionConfig } from "$lib/config.js";
  import type { SessionStatus } from "$lib/stores/session.svelte.js";

  let {
    connections,
    sessions,
    activeSessionId,
    collapsed,
    onToggle,
    onSelect,
    onAdd,
    onEdit,
    onDelete,
  }: {
    connections: ConnectionConfig[];
    sessions: Map<string, { id: string; name: string; status: SessionStatus }>;
    activeSessionId: string | null;
    collapsed: boolean;
    onToggle: () => void;
    onSelect: (conn: ConnectionConfig) => void;
    onAdd: () => void;
    onEdit: (conn: ConnectionConfig) => void;
    onDelete: (conn: ConnectionConfig) => void;
  } = $props();

  let searchQuery = $state("");

  const filteredConnections = $derived(
    connections.filter(
      (c) =>
        c.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.host.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.username.toLowerCase().includes(searchQuery.toLowerCase())
    )
  );

  function statusColor(status: SessionStatus): string {
    switch (status) {
      case "connected":
        return "bg-green-500";
      case "connecting":
        return "bg-yellow-500 animate-pulse";
      case "error":
        return "bg-red-500";
      default:
        return "bg-muted-foreground/50";
    }
  }

  function isConnected(conn: ConnectionConfig): boolean {
    return Array.from(sessions.values()).some(
      (s) => s.status === "connected" && s.name === `${conn.username}@${conn.host}:${conn.port}`
    );
  }

  function getConnectionSession(conn: ConnectionConfig): { id: string; name: string; status: SessionStatus } | undefined {
    return Array.from(sessions.values()).find(
      (s) => s.name === `${conn.username}@${conn.host}:${conn.port}`
    );
  }
</script>

<div
  class="sidebar flex flex-col border-r border-border bg-sidebar transition-all duration-200 {collapsed ? 'w-12' : 'w-72'}"
>
  <div class="flex items-center justify-between p-3 border-b border-border">
    {#if !collapsed}
      <div class="flex items-center gap-2">
        <Terminal class="size-4 text-primary" />
        <span class="text-sm font-semibold">Connections</span>
      </div>
    {/if}
    <Button variant="ghost" size="icon-xs" onclick={onToggle}>
      {#if collapsed}
        <ChevronRight class="size-3.5" />
      {:else}
        <ChevronLeft class="size-3.5" />
      {/if}
    </Button>
  </div>

  {#if !collapsed}
    <div class="p-3 space-y-2">
      <div class="relative">
        <Search class="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
        <Input
          bind:value={searchQuery}
          placeholder="Search connections..."
          class="pl-8 h-8 text-sm"
        />
      </div>
      <Button onclick={onAdd} variant="outline" size="sm" class="w-full gap-2">
        <Plus class="size-3.5" />
        Add Connection
      </Button>
    </div>

    <div class="flex-1 overflow-y-auto px-2 pb-2">
      {#each filteredConnections as conn (conn.id)}
        <button
          class="w-full text-left px-3 py-2.5 rounded-lg mb-1 transition-colors hover:bg-sidebar-accent group flex items-center gap-3 {(() => { const session = getConnectionSession(conn); return session && session.id === activeSessionId ? 'bg-sidebar-accent' : ''; })()}"
          onclick={() => onSelect(conn)}
        >
          <div class="flex flex-col min-w-0 flex-1">
            <div class="flex items-center gap-2">
              <span class="text-sm font-medium truncate">{conn.name}</span>
              <div class="size-2 rounded-full shrink-0 {(() => { const session = getConnectionSession(conn); return session ? statusColor(session.status) : 'bg-muted-foreground/50'; })()}"></div>
            </div>
            <span class="text-xs text-muted-foreground truncate">
              {conn.username}@{conn.host}:{conn.port}
            </span>
          </div>
          <div class="hidden group-hover:flex items-center gap-1 shrink-0">
            <Button
              variant="ghost"
              size="icon-xs"
              class="size-6"
              onclick={(e) => {
                e.stopPropagation();
                onEdit(conn);
              }}
            >
              <Pencil class="size-3" />
            </Button>
            <Button
              variant="ghost"
              size="icon-xs"
              class="size-6 text-destructive hover:text-destructive"
              onclick={(e) => {
                e.stopPropagation();
                onDelete(conn);
              }}
            >
              <Trash2 class="size-3" />
            </Button>
          </div>
        </button>
      {/each}

      {#if filteredConnections.length === 0}
        <div class="text-center py-8 text-muted-foreground text-sm">
          {#if searchQuery}
            No connections match "{searchQuery}"
          {:else}
            No connections yet
          {/if}
        </div>
      {/if}
    </div>
  {/if}
</div>

// src/components/layout/Sidebar.tsx
import { cn } from '@/lib/utils';
import { useSessionStore } from '@/lib/stores';
import { Terminal, Key, ArrowRightLeft, Folder, Plus, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import type { ViewType } from '@/lib/types';

const navItems = [
  { id: 'dashboard' as ViewType, label: 'Sessions', icon: Terminal },
  { id: 'keys' as ViewType, label: 'Keys', icon: Key },
  { id: 'portForwards' as ViewType, label: 'Port Forwards', icon: ArrowRightLeft },
];

interface SidebarProps {
  onNewSession: () => void;
}

export function Sidebar({ onNewSession }: SidebarProps) {
  const { currentView, setCurrentView, sessions, groups } = useSessionStore();

  const activeSessions = sessions.filter((s) => s.status === 'Connected').length;

  return (
    <div className="border-border bg-surface flex h-full w-64 flex-col border-r">
      {/* Header */}
      <div className="border-border flex h-14 items-center border-b px-4">
        <Terminal className="text-primary mr-2 h-5 w-5" />
        <span className="text-foreground text-lg font-bold">Noverterm</span>
      </div>

      {/* New Connection Button */}
      <div className="p-3">
        <Button
          onClick={onNewSession}
          className="bg-primary text-primary-foreground hover:bg-primary/90 h-10 w-full justify-start"
        >
          <Plus className="mr-2 h-4 w-4" />
          New Connection
        </Button>
      </div>

      <Separator />

      {/* Navigation */}
      <ScrollArea className="flex-1">
        <div className="space-y-1 p-2">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = currentView === item.id;
            const badge = item.id === 'dashboard' ? activeSessions : undefined;

            return (
              <button
                key={item.id}
                onClick={() => {
                  setCurrentView(item.id);
                }}
                className={cn(
                  'flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors',
                  isActive
                    ? 'bg-primary/20 text-primary'
                    : 'text-muted-foreground hover:bg-border hover:text-foreground'
                )}
              >
                <Icon className="h-4 w-4" />
                <span className="flex-1 text-left">{item.label}</span>
                {badge !== undefined && badge > 0 && (
                  <span
                    className={cn(
                      'flex h-5 min-w-5 items-center justify-center rounded-full px-1.5 text-xs',
                      isActive
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-muted text-muted-foreground'
                    )}
                  >
                    {badge}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Groups */}
        {groups.length > 0 && currentView === 'dashboard' && (
          <>
            <Separator className="my-2" />
            <div className="px-3 py-2">
              <div className="text-muted-foreground mb-2 flex items-center gap-2 text-xs font-semibold uppercase">
                <Folder className="h-3 w-3" />
                Groups
              </div>
              <div className="space-y-1">
                {groups.map((group) => (
                  <button
                    key={group.id}
                    className="text-muted-foreground hover:bg-border hover:text-foreground flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors"
                  >
                    <span
                      className="h-2 w-2 rounded-full"
                      style={{ backgroundColor: group.color }}
                    />
                    <span>{group.name}</span>
                    <span className="ml-auto text-xs">
                      {sessions.filter((s) => s.group === group.name).length}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </>
        )}
      </ScrollArea>

      <Separator />

      {/* Footer */}
      <div className="p-2">
        <button
          onClick={() => {
            setCurrentView('dashboard');
          }}
          className={cn(
            'flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors',
            'text-muted-foreground hover:bg-border hover:text-foreground'
          )}
        >
          <Settings className="h-4 w-4" />
          <span>Settings</span>
        </button>
      </div>
    </div>
  );
}
